parameters:
    proxies:
        - 123
        - 122

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    _instanceof:
        App\Factory\CS\Resolver\CSFactoryInterface:
            tags: [cs.factory]
        App\Service\ResourceAPIs\APIResourceInterface:
            tags: [api.resource]

    App\Factory\CS\Resolver\CSFactoryResolver:
        arguments: [!tagged cs.factory]

    App\Service\ResourceAPIs\Resolver\ResourceAPIsResolver:
        arguments: [!tagged api.resource]
