services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Http\Controller\:
        resource: '../src/Http/Controller'
        tags: ['controller.service_arguments']

    _instanceof:
        App\Domain\Factory\CS\CSFactoryInterface:
            tags: [cs.factory]

        App\Application\Resources\ApiResourceInterface:
            tags: [api.resource]

        App\Application\Config\ConfigInterface:
            tags: [app.config]

        App\Application\Tools\DecisionMaker\DecisionMakerInstanceInterface:
            tags: [decision.instance]

    App\Domain\Factory\CS\CSFactoryResolver:
        arguments: [!tagged cs.factory]

    App\Application\Resources\ApiResourceResolver:
        arguments: [!tagged api.resource]

    App\Application\Config\ConfigResolver:
        arguments: [!tagged app.config]

    App\Application\Tools\DecisionMaker\DecisionMaker:
        arguments: [!tagged decision.instance]