parameters:
    proxies:
        - 123
        - 122

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    _instanceof:
        App\Domain\Factory\CS\Resolver\CSFactoryInterface:
            tags: [cs.factory]

        App\Application\Resources\ApiResourceInterface:
            tags: [api.resource]

        App\Application\Config\ConfigInterface:
            tags: [app.config]

    App\Domain\Factory\CS\Resolver\CSFactoryResolver:
        arguments: [!tagged cs.factory]

    App\Application\Resources\ApiResourceResolver:
        arguments: [!tagged api.resource]

    #config
    App\Application\Config\ConfigResolver:
        arguments:
            - !tagged api.resource
            - '%kernel.project_dir%'
